### ISSUE TITLE
Overhaul Organization

### ISSUE THREAD

**Issue by mdefende** [uabrc/researcher_facing_readthedocs#44]
Need to discuss overall organization of the pages. Adding clustered subsections like we have now will make the TOC unwieldy long-term as more and more gets added. For this, I like how Auburn has organized theirs where everything is under a User Guide section for each of their overall resources. Translated to us, this would mean Cheaha and UAB Cloud would be totally separate User Guides, and those would be the only things seen in the TOC sidebar when someone comes to the front page of the docs. Should talk about soon

**Comment by mdefende** [comment]
https://hpc.auburn.edu/hpc/docs/hpcdocs/build/html/index.html

**Comment by wwarriner** [comment]
Great idea, totally agree. It's getting to time where we have to reorganize.

As we do this, it may be worth making an FAQ-style page, either as the index, or an "alternate" index. The FAQ answers can link to relevant sections in the docs.

**Comment by wwarriner** [comment]
We started this process today. The relevant shared document is at UAB's [box.com instance](https://uab.app.box.com/file/860492439458?s=2onvcehsrarzx2uusuycc97v22pphaa7)

**Comment by mdefende** [comment]
This issue has been basically resolved by pull #62. Future additions will cause some change to the organization, but the general format will remain as is
