### ISSUE TITLE
Array job index hotfix

### ISSUE THREAD

**Issue by mdefende** [uabrc/researcher_facing_readthedocs#53]
Array job indexes are incorrect in the examples. They are represented as 1's based but in actuality are 0's based.

**Comment by wwarriner** [comment]
Can you link to the pages for whoever works on this?

Do you mean the `--array` flag itself? That is whatever you decide it should be in a comma-separated, hyphenated list (e.g. 2,3,5-7)

Or do you mean bash arrays? Those are definitely 0-indexed

**Comment by mdefende** [comment]
I'm working on it. The --array example on the page explains it as if it's 1's-based indexing, but it will be changed to 0's based.

**Comment by mdefende** [comment]
This issue has been resolved in pull request #62
